# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 0, "", "kvstore.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rkvstore.proto\x12\x07kvstore"U\n\nPutRequest\x12\x10\n\x03key\x18\x01 \x01('
    b"\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n\x0bttl_seconds\x18\x03 \x01("
    b'\x05R\nttlSeconds"\r\n\x0bPutResponse"\x1e\n\nGetRequest\x12\x10\n\x03key\x18\x01 \x01('
    b'\tR\x03key"#\n\x0bGetResponse\x12\x14\n\x05value\x18\x01 \x01('
    b'\tR\x05value"!\n\rDeleteRequest\x12\x10\n\x03key\x18\x01 \x01('
    b'\tR\x03key"\x10\n\x0e\x44\x65leteResponse"%\n\x0bListRequest\x12\x16\n\x06prefix\x18\x01 \x01('
    b'\tR\x06prefix"2\n\x08KeyValue\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01('
    b"\tR\x05value\"7\n\x0cListResponse\x12'\n\x05items\x18\x01 \x03("
    b"\x0b\x32\x11.kvstore.KeyValueR\x05items2\xe3\x01\n\rKeyValueStore\x12\x30\n\x03Put\x12\x13.kvstore.PutRequest"
    b"\x1a\x14.kvstore.PutResponse\x12\x30\n\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12\x39\n"
    b"\x06\x44\x65lete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse\x12\x33\n\x04List\x12\x14.kvstore"
    b".ListRequest\x1a\x15.kvstore.ListResponseb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "kvstore_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PUTREQUEST"]._serialized_start = 26
    _globals["_PUTREQUEST"]._serialized_end = 111
    _globals["_PUTRESPONSE"]._serialized_start = 113
    _globals["_PUTRESPONSE"]._serialized_end = 126
    _globals["_GETREQUEST"]._serialized_start = 128
    _globals["_GETREQUEST"]._serialized_end = 158
    _globals["_GETRESPONSE"]._serialized_start = 160
    _globals["_GETRESPONSE"]._serialized_end = 195
    _globals["_DELETEREQUEST"]._serialized_start = 197
    _globals["_DELETEREQUEST"]._serialized_end = 230
    _globals["_DELETERESPONSE"]._serialized_start = 232
    _globals["_DELETERESPONSE"]._serialized_end = 248
    _globals["_LISTREQUEST"]._serialized_start = 250
    _globals["_LISTREQUEST"]._serialized_end = 287
    _globals["_KEYVALUE"]._serialized_start = 289
    _globals["_KEYVALUE"]._serialized_end = 339
    _globals["_LISTRESPONSE"]._serialized_start = 341
    _globals["_LISTRESPONSE"]._serialized_end = 396
    _globals["_KEYVALUESTORE"]._serialized_start = 399
    _globals["_KEYVALUESTORE"]._serialized_end = 626
# @@protoc_insertion_point(module_scope)
